FROM node:alpine AS build

LABEL org.opencontainers.image.description="Static build of sulej.ch"

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build

RUN mkdir -p /output && cp -r /app/build/. /output/

VOLUME /output
