name: Deploy docker

on:
  push:
    tags:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  docker-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GH_USERNAME }}" --password-stdin

      - name: Get version tag
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 || echo latest)" >> $GITHUB_ENV

      - name: Build & Push sulej.ch:build
        run: |

          docker buildx create --use

          docker buildx build --platform linux/amd64 -f Dockerfile.build \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/${{ vars.IMAGE_NAME }}:build-latest \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/${{ vars.IMAGE_NAME }}:build-${VERSION} \
            --push --provenance=false .

      - name: Build & Push sulej.ch
        run: |

          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386,linux/ppc64le,linux/riscv64,linux/s390x \
            --build-arg BUILD_IMAGE="ghcr.io/${{ secrets.GH_USERNAME }}/${{ vars.IMAGE_NAME }}:build-latest" \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/${{ vars.IMAGE_NAME }}:latest \
            -t ghcr.io/${{ secrets.GH_USERNAME }}/${{ vars.IMAGE_NAME }}:${VERSION} \
            --push --provenance=false .
